export const Skill_data = [
  {
    skill_name: "Html 5",
    category: "language",
    Image: "/skills/html.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "CSS",
    category: "language",
    Image: "/skills/css.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Javascript",
    category: "language",
    Image: "/skills/js.png",
    width: 65,
    height: 65,
  },
  {
    skill_name: "PHP",
    category: "language",
    Image: "/skills/php.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "C#",
    category: "language",
    Image: "/skills/csharp.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Java",
    category: "language",
    Image: "/skills/java.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Dart",
    category: "language",
    Image: "/skills/dart.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Typescript",
    category: "language",
    Image: "/skills/ts.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Node JS",
    category: "language",
    Image: "/skills/html.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Python",
    category: "language",
    Image: "/skills/python.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Laravel",
    category: "framework",
    Image: "/skills/laravel.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "React JS",
    category: "framework",
    Image: "/skills/react.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Flutter",
    category: "framework",
    Image: "/skills/flutter.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "React Native",
    category: "framework",
    Image: "/skills/reactnative.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: ".NET",
    category: "framework",
    Image: "/skills/dotnet.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Java Enterprise Edition",
    category: "framework",
    Image: "/skills/javaee.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Tailwind/Nativewind",
    category: "framework",
    Image: "/skills/tailwind.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Next JS",
    category: "framework",
    Image: "/skills/next.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "MySQL",
    category: "database",
    Image: "/skills/mysql.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "SQLite",
    category: "database",
    Image: "/skills/sqlite.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "MSSQL",
    category: "database",
    Image: "/skills/mssql.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Firebase",
    category: "database",
    Image: "/skills/firebase.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Git",
    category: "others",
    Image: "/skills/git.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "GitHub",
    category: "others",
    Image: "/skills/github.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "GitLab",
    category: "others",
    Image: "/skills/gitlab.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Ubuntu VPS",
    category: "others",
    Image: "/skills/ubuntu.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Windows VPS",
    category: "others",
    Image: "/skills/windows.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Cloudflare",
    category: "others",
    Image: "/skills/cloudflare.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Android Studio",
    category: "others",
    Image: "/skills/androidstudio.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Nginx",
    category: "others",
    Image: "/skills/nginx.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "IIS Server",
    category: "others",
    Image: "/skills/iis.png",
    width: 80,
    height: 80,
  },
  {
    skill_name: "Laragon",
    category: "others",
    Image: "/skills/laragon.png",
    width: 80,
    height: 80,
  },
];

export const Links = [
    {
        name: "LinkedIn",
        src: "/images/socials/linkedin.svg"
    },
    {
        name: "GitHub",
        src: "/images/socials/github.svg"
    }
]